name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.arch }}-unknown-linux-gnu

      - name: Build project
        run: |
          cargo build --release --target ${{ matrix.arch }}-unknown-linux-gnu

      - name: Archive binary
        run: |
          zip -j ${{ matrix.os }}-${{ matrix.arch }}.zip target/${{ matrix.arch }}-unknown-linux-gnu/release/*

      - name: Calculate SHA256
        id: sha256
        run: |
          sha256sum ${{ matrix.os }}-${{ matrix.arch }}.zip > ${{ matrix.os }}-${{ matrix.arch }}.zip.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ${{ matrix.os }}-${{ matrix.arch }}.zip
            ${{ matrix.os }}-${{ matrix.arch }}.zip.sha256

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload release assets
        run: |
          for file in artifacts/*; do
            gh release upload ${{ github.ref_name }} "$file" --clobber;
          done
