name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}-unknown-linux-gnu

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build project
        run: |
          rustup target add ${{ matrix.arch }}-unknown-linux-gnu
          cargo build --release --target=${{ matrix.arch }}-unknown-linux-gnu

      - name: Package build
        run: |
          zip -j ${{ matrix.os }}-${{ matrix.arch }}.zip target/${{ matrix.arch }}-unknown-linux-gnu/release/rustora

      - name: Calculate SHA256
        id: sha256
        run: |
          sha256sum ${{ matrix.os }}-${{ matrix.arch }}.zip > ${{ matrix.os }}-${{ matrix.arch }}.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ${{ matrix.os }}-${{ matrix.arch }}.zip
            ${{ matrix.os }}-${{ matrix.arch }}.sha256

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_name: ${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_content_type: application/zip

      - name: Upload SHA256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.os }}-${{ matrix.arch }}.sha256
          asset_name: ${{ matrix.os }}-${{ matrix.arch }}.sha256
          asset_content_type: text/plain